#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
mkdir -p ~/lightnvr && cd ~/lightnvr
cd ~/lightnvr
nano docker-compose.yml

docker-compose up -d


echo "Instalasi selesai!"
