#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
yes | apt install -y docker-compose
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
mkdir -p ~/lightnvr && cd ~/lightnvr
cd ~/lightnvr
sudo wget -O docker-compose.yml https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/CCTV

echo "Compose"
cd ~/lightnvr
docker-compose up -d


echo "Instalasi selesai!"
