#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
curl -fsSL https://get.docker.com | sh
sudo systemctl start docker
sudo systemctl enable docker

echo "Instalasi selesai!"
