#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
yes | sudo apt update -y
yes | sudo apt-get install -y ntfsprogs
yes | sudo apt-get install -y nfs-kernel-server

sudo bash -c 'cat << "EOF" > /etc/exports
/mnt/External/cctv 192.168.18.20(rw,sync,no_subtree_check,no_root_squash)
EOF'
sudo exportfs -a
sudo systemctl restart nfs-kernel-server
sudo systemctl enable nfs-kernel-server
sudo mount -v -t nfs 192.168.18.2:/mnt/External/cctv /root/motioneye/storage

sudo ntfsfix /dev/sda1
sudo gedit fstab
mkdir /mnt/External
mount /dev/sda1 /mnt/External
DRIVE_CONF="/etc/fstab"
cp $DRIVE_CONF "$DRIVE_CONF.bak"
echo "[+] Menulis konfigurasi DRIVE ke FSTAB..."
cat <<EOT >> $DRIVE_CONF
UUID="EAFE72BDFE72819D" /mnt/External    ntfs-3g   defaults,nofail,noatime  0  2
UUID="6CFC6F3FFC6F02A6" /mnt/External    ntfs-3g   defaults,nofail,noatime  0  2
UUID="5E5E85795E854AAB" /mnt/External    ntfs-3g   defaults,nofail,noatime  0  2
UUID="1E4C64934C64678B" /mnt/External    ntfs-3g   defaults,nofail,noatime  0  2
UUID="104A4F424A4F23B6" /mnt/External    ntfs-3g   defaults,nofail,noatime  0  2
UUID="CEC6AE70C6AE590B" /mnt/External    ntfs-3g   defaults,nofail,noatime  0  2

EOT


echo "Instalasi selesai!"
