#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
sudo apt install docker.io docker-compose -y
mkdir -p ~/gopeed/Downloads ~/gopeed/storage
cd ~/gopeed
sudo wget -O docker-compose.yml https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Gopeed
docker-compose up -d

echo "Instalasi selesai!"
