#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
sudo wget -O nano /etc/network/interfaces.d/*
# Network is managed by Network manager
auto eth0
iface eth0 inet dhcp

hwaddress ether 00:15:18:01:81:31
iface lo inet loopback

echo "Instalasi selesai!"
