#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
yes | sudo apt update && sudo apt install docker-compose
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
mkdir ~/n8n && cd ~/n8n
cd ~/n8n
curl -sSL https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/n8n -o docker-compose.yml
echo "Konfigurasi n8n berhasil dipasang!"
docker-compose up -d

cd ~/n8n
nano docker-compose.yml

echo "Instalasi selesai!"
