#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
yes | sudo apt-get install cups printer-driver-gutenprint p910nd hplip printer-driver-foo2zjs -y
yes | sudo apt install sane sane-utils simple-scan xsane nmap netcat-openbsd -y
sudo add-apt-repository ppa:thierry-f/fork-michael-gruz -y
yes | sudo apt install sane-backends -y
yes | sudo apt install sane-frontends -y
sudo nmap 192.168.18.2
yes | sudo apt install kmod-usb-printer p910nd luci-app-p910ndkmod-usb-printer -y
sudo systemctl start cups
sudo systemctl enable cups
sudo systemctl restart cups
sudo service cups restart
sudo systemctl status cups
sudo systemctl enable cups.service
sudo systemctl status cups.service
yes | sudo apt install scangearmp2 -y
yes | sudo apt install printer-driver-cnijfilter-mg4200 -y
yes | sudo apt install cnijfilter2 -y
yes | sudo apt install avahi-daemon -y
sudo systemctl start avahi-daemon
sudo useradd -g lpadmin cupsadmin
sudo usermod -a -G lpadmin dadi
sudo passwd cupsadmin

sudo passwd dadi

sudo cupsctl --remote-any
sudo chmod +x /usr/local/bin/jetdirect.sh
sudo systemctl daemon-reload
sudo systemctl start jetdirect
sudo systemctl enable jetdirect
sudo killall cupsd
sudo sed -i 's@#192.168.0.1@#192.168.18.2@g' /etc/sane.d/saned.conf
sudo sed -i 's@#192.168.0.0/29@#192.168.18.0/29@g' /etc/sane.d/saned.conf
nano /etc/sane.d/saned.conf
nano /etc/cups/cupsd.conf
echo "Menginstal aplikasi Saned"
sudo wget -O /etc/default/saned https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Saned
echo "Menginstal aplikasi Jetdirect"
sudo wget -O /usr/local/bin/jetdirect.sh https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Jetdirect
sudo chmod +x /usr/local/bin/jetdirect.sh
echo "Menginstal aplikasi Jetdirect_Service"
sudo wget -O /etc/systemd/system/jetdirect.service https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Jetdirect_Service
echo "Menginstal aplikasi p910nd"
sudo wget -O /etc/default/p910nd https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/p910nd
sudo /etc/init.d/cups restart
sudo systemctl daemon-reload
sudo systemctl start jetdirect
sudo systemctl enable jetdirect
sudo killall cupsd
sudo /etc/init.d/cups restart
sudo systemctl enable avahi-daemon

echo "Instalasi selesai!"
