#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
sudo apt install git -y
git clone https://gitlab.com/Shinobi-Systems/Shinobi.git Shinobi
cd Shinobi
sudo chmod +x INSTALL/ubuntu.sh
sudo INSTALL/ubuntu.sh
expect {
    # Do you want to Install MariaDB? Choose No if you already have it.
    -re "Do you want to Install MariaDB? Choose No if you already have it.*" {
        send "y\r"
        exp_continue
    }
    # Password for root SQL user, If you are installing SQL now then you may put anything:
    -re "Password for root SQL user, If you are installing SQL now then you may put anything:*" {
        send "980Abc\r"
        exp_continue
    }
    # Shinobi - Database Installation
    -re "Shinobi - Database Installation*" {
        send "y\r"
        exp_continue
    }
    # Shinobi - Start Shinobi and set to start on boot?
    -re "Shinobi - Start Shinobi and set to start on boot?*" {
        send "y\r"
        exp_continue
    }
    # Menangani akhir dari proses script
    eof
}
EOF

echo "Instalasi selesai!"
