#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
sudo apt install git -y
git clone https://gitlab.com/Shinobi-Systems/Shinobi.git Shinobi
cd Shinobi
sudo chmod +x INSTALL/ubuntu.sh
sudo INSTALL/ubuntu.sh
cd /root/Shinobi
npm install --loglevel verbose
node -v
npm -v
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
source ~/.bashrc
nvm install 22
nvm use 22
npm i npm -g
rm -rf node_modules package-lock.json
npm cache clean --force
npm install --legacy-peer-deps
sudo apt install build-essential python3 libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev -y
sh UPDATE.sh
pm2 flush
pm2 restart camera
pm2 logs


echo "Instalasi selesai!"
