#!/bin/bash

# 1. Pastikan script dijalankan sebagai root
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

# 2. Pastikan paket 'expect' dan 'git' sudah terinstal
echo "Memeriksa dan menginstal dependensi awal..."
sudo apt update
sudo apt install git -y
git clone https://gitlab.com/Shinobi-Systems/Shinobi.git Shinobi
cd Shinobi
sudo chmod +x INSTALL/ubuntu.sh
sudo INSTALL/ubuntu.sh

# 3. Bagian ini yang menjalankan perintah otomatisnya
images_tags=$(expect << 'EOF'
set timeout -1
spawn sudo INSTALL/ubuntu.sh

expect {
    -re "Do you want to Install MariaDB.*" {
        send "y\r"
        exp_continue
    }
    -re "Password for root SQL user.*" {
        send "980Abc\r"
        exp_continue
    }
    -re "Database Installation.*" {
        send "y\r"
        exp_continue
    }
    -re "Start Shinobi and set to start on boot.*" {
        send "y\r"
        exp_continue
    }
    eof
}
EOF
)

echo "Instalasi selesai!"
