#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
sudo apt install mpd
#UNDER THE AUDIO OUTPUT#

sudo tee -a /etc/mpd.conf > /dev/null << 'EOF'

# Audio Output ################################################################
#
sudo sed -i 's/# Audio Output ################################################################
#/# Audio Output ################################################################
#
audio_output {
    type            "alsa"  # or "pulse" depending on your setup
    name            "432Hz Output"
    auto_resample   "no"
    format          "44100:16:2"
    mixer_type      "software"
}
resampler {
    plugin          "sox"
    quality         "high"
}/g' /etc/mpd.conf
EOF

sudo nano /etc/mpd.conf
sudo systemctl restart mpd

DAEMON_CONF="/etc/pulse/daemon.conf"
cp $DAEMON_CONF "$DAEMON_CONF.bak"
echo "[+] Menulis konfigurasi DAEMON_CONF..."
cat <<EOT >> $DAEMON_CONF

; default-sample-format = s24le
; default-sample-rate = 192000
; resample-method = soxr-vhq
; pulseaudio -k && pulseaudio -D
EOT

echo "Instalasi selesai!"
