#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
sudo apt install unbound dnsutils net-tools tcpdump -y
dig -v

echo "Copy Configuration Unbound..."
sudo wget -O /etc/unbound/unbound.conf.d/unboundadguard.conf https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Unbound2
sudo wget -O /etc/unbound/unboundadguard.conf https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Unbound2

sudo sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
sudo systemctl restart systemd-resolved
sudo wget https://internic.net -O /var/lib/unbound/root.hints
sudo wget https://www.internic.net/domain/named.root -O /var/lib/unbound/root.hints
sudo unbound-checkconf

sudo systemctl restart unbound
sudo systemctl enable unbound
sudo systemctl status unbound

cd /etc/unbound
netstat -anput
ip addr
tcpdump -^C
whereis tcpdump
usr/sbin/tcpdump -ni enp0s3 udp port 53

dig somebadsites.com @127.0.0.1 -p 5335
dig fail2000.dnssec-failed.org @127.0.0.1 -p 5335
dig dnssec-failed.org @127.0.0.1 -p 5335

tcpdump -ni ^C
usr/sbin/tcpdump -ni enp0s3 udp port 53

dig @192.168.18.9 somebadsites.com

echo "Instalasi selesai!"
