#!/bin/bash

# Pastikan script dijalankan sebagai root (administrator)
if [ "$EUID" -ne 0 ]; then
  echo "Harap jalankan script ini sebagai root (gunakan sudo)"
  exit 1
fi

echo "Menginstal aplikasi..."
# Ganti dengan paket yang ingin Anda install, contoh:
yes | sudo apt update -y
sudo apt install unbound unbound-anchor dnsutils net-tools tcpdump -y
dig -v

echo "Copy Configuration Unbound..."
sudo wget -O /etc/unbound/unbound.conf.d/unbound.conf https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Unbound3
sudo wget -O /etc/systemd/system/apt-auto-update.service https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Unbound4
sudo wget -O /usr/local/sbin/apt-auto-update.sh https://raw.githubusercontent.com/hdadis/Script/refs/heads/main/Unbound5

sudo sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
sudo systemctl restart systemd-resolved
sudo wget https://internic.net -O /var/lib/unbound/root.hints
sudo wget https://www.internic.net/domain/named.root -O /var/lib/unbound/root.hints
sudo chmod +x /usr/local/sbin/apt-auto-update.sh
sudo unbound-checkconf

sudo unbound-anchor -a /etc/unbound/root.key


sudo systemctl restart unbound
sudo systemctl enable unbound
sudo systemctl status unbound

cd /etc/unbound
netstat -anput
ip addr
tcpdump -^C
whereis tcpdump
/usr/bin/tcpdump -ni enp0s3 udp port 53

dig sigok.verteiltesysteme.net @127.0.0.1
dig sigfail.verteiltesysteme.net @127.0.0.1
dig dnssec-failed.org @127.0.0.1 -p 5335

dig @192.168.18.9 somebadsites.com

echo "Instalasi selesai!"
